### ISSUE TITLE
Cannot transition from hypervisor el2_kernel.img to standard kernel

### ISSUE THREAD

**Issue by SikkiLadho** [SikkiLadho/Leo#1]
Hypervisor successfully prints Hello World to UART. It needs to jump into standard kernel with exception level el2. 

We are using [this function](https://github.com/SikkiLadho/Leo/blob/d60a9cc73671570f55e2da7595003705e4ba9150/src/utils.S#L17) to jump from any exception level to el1 and to address 0x200000 

There is a way to load two binaries in raspberry pi.
in config.tx, [initramfs configuration](https://github.com/SikkiLadho/Leo/blob/2e3b8e9e5339f3f544b4bd6d00c5ce4883ddf63c/raspberrypi_config.txt#L12) loads kernel at 0x200000. 

In theory, hypervisor should pass the control to standard kernel, but it is stuck after printing hello world.

Update:

- [x] all the requirements should be met for the kernel explained in /Documentation/arm64/booting.rst

**Comment by YWHyuk** [comment]
Hi, @SikkiLadho
I saw this issue in the kernel newbie mailing list
Is this issue fixed?

**Comment by SikkiLadho** [comment]
> 

@YWHyuk, we have not been able to fix it. I'm trying to study halfnium code to see how they have solved it.

**Comment by YWHyuk** [comment]
@SikkiLadho 
Does the example of ["Bare-metal Boot Code for ARMv8-A"](https://developer.arm.com/documentation/dai0527/a/) not worked?

**Comment by SikkiLadho** [comment]
@YWHyuk 

I have not yet tried it. I will try it soon and also study the hafnium code as the working implementation.

**Comment by SikkiLadho** [comment]
Closing the issue. There was no problem with the code. Strangely, kernel won't boot when compiled with "aarch64-linux-gnu-" native apt package. Kernel is booting successfully(although there are a few issues, but least we can see earlier kernel boot messages.)  

This was a very annoying error, since Raspberry [docs](https://www.raspberrypi.com/documentation/computers/linux_kernel.html#install-required-dependencies-and-toolchain) use the Debian Package "aarch64-linux-gnu-" for cross-compiling the kernel. For now, kernel would boot if only compiled with GNU Toolchain provided by ARM. https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads .



We are still learning to find out reasons for this behavior.  

cc: @YWHyuk
