### ISSUE TITLE
Error: Kernel panic - not syncing:

### ISSUE THREAD

**Issue by SikkiLadho** [SikkiLadho/Leo#2]
We are facing the Kernel panic. Following the UART log output: 

UART Log: 
https://pastebin.mozilla.org/er67cUTn

We have to look at the first errors: 

> [ 1.750626] rootfs image is not initramfs (invalid magic at start of compress ed archive); looks like an initrd
> [ 1.810959] Unable to handle kernel write to read-only memory at virtual addr ess ffffff8000400000

It seems kernel is looking for an initramfs file, but kernel in raspian OS doesn't not use initrd or initramfs file. It is because, we have abused the ["initramfs" config](https://www.raspberrypi.com/documentation/computers/config_txt.html#initramfs) to load the load the linux kernel. Initramfs config is used to provide initramfs and initrd files to the kernel. 

Firmware believes that we are loading the initramfs file, therefore it adds an entry about initramfs to the dtb file at the runtime but there's no initramfs image at  ffffff8000400000, it is the kernel itself. 

What we have to is to clear the "initrd" field added by the firmware to dtb. 

We can edit the dtb blobs at runtime in the hypervisor, by utilizing [libfdt library](https://git.kernel.org/pub/scm/utils/dtc/dtc.git).

**Comment by SikkiLadho** [comment]
@paranlee @OsamaMuhammadd 

I have updated the issue. Feel free to add your thoughts.

**Comment by SikkiLadho** [comment]
~~We also have a warning.~~

> [ 0.000000] WARNING: x1-x3 nonzero in violation of boot protocol:
[ 0.000000] x1: 00000000003ffee0
[ 0.000000] x2: 0000000000000018
[ 0.000000] x3: ffffffffffffffff
[ 0.000000] This indicates a broken bootloader or old kernel

~~It seems we have not zeroed out x1-x3 as defined in the [arm64/booting.rst](https://mjmwired.net/kernel/Documentation/arm64/booting.rst#159).~~


Created a new issue: https://github.com/SikkiLadho/Leo/issues/5

**Comment by osmten** [comment]
We have Resolved the issue. Now we can boot without any errors.
